name: Build

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: Build Win10 x64
    runs-on: windows-latest

    env:
      configuration: Release
      Main_Project: Ui/Ui.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('Ui/Ui.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: msbuild $env:Main_Project /t:Restore /p:Configuration=$env:Configuration

      - name: Replace secrets (if available)
        shell: pwsh
        run: |
          if ("${{ secrets.APP_CENTER_SECRET_1REMOTE }}") {
            ./scripts/Set-Secret.ps1 -filePath .\Ui\Assert.cs -Pattern "===REPLACE_ME_WITH_APP_CENTER_SECRET===" -Secret "${{ secrets.APP_CENTER_SECRET_1REMOTE }}"
          }
          if ("${{ secrets.SENTRY_IO_DEN }}") {
            ./scripts/Set-Secret.ps1 -filePath .\Ui\Assert.cs -Pattern "===REPLACE_ME_WITH_SENTRY_IO_DEN===" -Secret "${{ secrets.SENTRY_IO_DEN }}"
          }
          if ("${{ secrets.GLOBAL_STRING_ENCRYPTION_SLAT }}") {
            ./scripts/Set-Secret.ps1 -filePath .\Ui\Assert.cs -Pattern "===REPLACE_ME_WITH_SALT===" -Secret "${{ secrets.GLOBAL_STRING_ENCRYPTION_SLAT }}"
          }

      - name: Get Version
        id: get_version
        run: ./scripts/Get-Version.ps1

      - name: Publish x64 self-contained
        run: dotnet publish $env:Main_Project -p:PublishProfile=./Ui/Properties/PublishProfiles/x64-net90-self-contained.pubxml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1Remote-${{ steps.get_version.outputs.BuildVersion }}-win10-x64
          path: Ui/bin/Release/net9.0-windows-self-contained/publish/win-x64
          retention-days: 30
